### ISSUE TITLE
Using functions in sequence

### ISSUE THREAD

**Issue by oe8bck** [rpm2003rpm/vagen#1]
Hi,

I like this module a lot, I am using it a lot. But I have a question which popped up when I was writing the sequence a little bit more structured. Maybe (I hope so) it's just a question of the syntax.

How to write it, when I would like to "call a function" in the sequence, e.g. a modification of the example from the README:

```
def firstSeq():
    VDD.setRiseFall(10e-6, 10e-6),
    VDD.applyV(5.0),
    va.WaitUs(10), 
    CLK.on(4e6),
    va.WaitUs(1),

#Sequence
mod.seq(True)(
    firstSeq(),
    RST.write(True),
    va.WaitSignal(EVNT_READY),
    OUT.setRiseFall(100e-9, 100e-9),
    OUT.applyI(100e-3), #Positive current enters the model
    va.WaitUs(10),

```    CONFIG_VOUT.write(5),
    va.WaitUs(20),
    va.Finish()
)
```

Many thanks for the module and all your support!
KR,
Christof

**Comment by rpm2003rpm** [comment]
Hello Christof, 

I'm glad to here that the module is useful to you.  Sequences accept two types of classes: veriloga.Cmd and veriloga.CmdList. As the name suggests, veriloga.CmdList holds a list of veriloga.Cmd objects. Therefore, one way to implement what you need is:

`
def firstSeq():
    return va.CmdList(
        VDD.setRiseFall(10e-6, 10e-6),
        VDD.applyV(5.0),
        va.WaitUs(10), 
        CLK.on(4e6),
        va.WaitUs(1)
    )

#Sequence
mod.seq(True)(
    firstSeq(),
    RST.write(True),
    va.WaitSignal(EVNT_READY),
    OUT.setRiseFall(100e-9, 100e-9),
    OUT.applyI(100e-3), #Positive current enters the model
    va.WaitUs(10),
    CONFIG_VOUT.write(5),
    va.WaitUs(20),
    va.Finish()
)
`

KR, 

Rodrigo

**Comment by oe8bck** [comment]
Thanks a lot for the fast response, this way it works!
